const tintColor = '#2f95dc';

export default {
  title: '#969292',
  titleDark: '#4D4A4A',
  titleLight: '#E3DCDC',
  cardBatang: 'white',
  batangLight: '#E3DCDC',
  batangDark: '#4D4A4A',
  batang: '#7A7373',
  point: '#FDCA24',
  pointDark: '#F6C31F',
  point2: '#00A651',
  indicator: '#FDCA24',
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  errorBG: '',
  errorText: 'red',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
};
